/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Multithreadedwordproject;

import java.io.File;
import java.util.NoSuchElementException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        /*
        This program will process a file by counting all the words in it and
        counting each word's length
        */
        timeKeeper timer = new timeKeeper();
        long lengthCounter = 0;
        int wordCounter = 0;
        ThreadBase base = new ThreadBase();
        
        File wordObj = new File("D:\\Java-software\\words-medium.txt");
        try {
            Scanner reader = new Scanner(wordObj);
            timer.startTimer();
            //multithreading will be handled from here
            base.setInputStream(reader);
            ThreadController controller = new ThreadController (base);
            CountThread counter = new CountThread (base);
            controller.t.start();
            counter.t.start();
            try {
                controller.t.join();
                counter.t.join();
            } catch (Exception e) {
                System.out.println("Interrupted");
            }
            lengthCounter = base.getWordLegnth();
            wordCounter = base.getWordAmount();
            
            long elapseTime = timer.elpasedTime();
            System.out.println("Total amount of words: " + wordCounter);
            System.out.println("Average word length is: " + lengthCounter / wordCounter);
            System.out.println("Total elapsed time is: " + elapseTime);
            reader.close();
            
        } 
        catch (Exception ex) {
            System.out.println("An error occured:" + ex.toString());
        }
    }
}
